### ISSUE TITLE
URL del repo incorrecta

### ISSUE THREAD

**Issue by hhkaos** [JorgeTasio/JorgeTasio.gibhub.io#1]
Buenas Jorge!

Me he dado cuenta que has creado el repo con la URL incorrecta, para arreglarlo tienes que:

1. Ir a [los settings del proyecto](https://github.com/JorgeTasio/JorgeTasio.gibhub.io/settings) y cambiar el nombre -> github en lugar de gibhub
2. Abrir la consola, ir a la carpeta del repositorio y ejecutar: <br>```$ git remote remove origin```
3. Y a continuación ejecutar: <br>```$ git remote add origin git@github.com:JorgeTasio/JorgeTasio.github.io.git```

Y con esto en principio ya podrás trabajar como si nunca hubiese pasado nada y la URL: [https://JorgeTasio.github.io](https://JorgeTasio.github.io) mostrará tu CV

Abrazo!

**Comment by JorgeTasio** [comment]
Muchas gracias Raúl, no he podido hacerlo hasta ahora pero lo he conseguido
Otro abrazo!

**Comment by hhkaos** [comment]
Genial Jorge, cierro el issue :)
